apiVersion: v1
kind: Pod
metadata:
  name: persistent
spec:
  containers:
  - name: container
    image: alpine
    command:
    - sleep
    - 24h
    volumeMounts:
    - name: pv-data
      mountPath: /usr/share/persistent
      readOnly: false
  volumes:
  - name: pv-data
    persistentVolumeClaim:
      claimName: pv-claim