apiVersion: v1
kind: Service
metadata:
  name: grapes-source
  labels:
    app: grapes-source
    group: grapes
spec:
  selector:
    app: grapes-source
    group: grapes
  ports:
  - name: web
    port: 80
    targetPort: web
---
apiVersion: apps/v1beta2
kind: ReplicaSet
metadata:
  name: grapes-source 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grapes-source
      group: grapes
  template:
    metadata:
      labels:
        app: grapes-source
        group: grapes
    spec:
      containers:
      - name: grapes-source 
        image: "maliksalman/grapes-source:1.0.0"
        imagePullPolicy: Always
#        command:
#          - sleep
#          - "1h"
        ports:
        - name: web
          containerPort: 8080
        resources:
          requests:
            memory: "500Mi"
            cpu: "375m"
          limits:
            memory: "768Mi"
            cpu: "500m"
        env:
          - name: NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: CONTAINER_MEM_MB
            valueFrom:
              resourceFieldRef:
                resource: limits.memory
                divisor: 1Mi
---
apiVersion: apps/v1beta2
kind: ReplicaSet
metadata:
  name: grapes-sink 
spec:
  replicas: 2
  selector:
    matchLabels:
      app: grapes-sink
      group: grapes
  template:
    metadata:
      labels:
        app: grapes-sink
        group: grapes
    spec:
      containers:
      - name: grapes-sink 
        image: "maliksalman/grapes-sink:1.0.0"
        imagePullPolicy: Always
        resources:
          requests:
            memory: "500Mi"
            cpu: "375m"
          limits:
            memory: "768Mi"
            cpu: "500m"
        env:
          - name: NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: GRAPES_CONSUMER_GROUP
            value: real-grapez
---
apiVersion: apps/v1beta2
kind: ReplicaSet
metadata:
  name: raisins-sink 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: raisins-sink
      group: grapes
  template:
    metadata:
      labels:
        app: raisins-sink
        group: grapes
    spec:
      containers:
      - name: raisins-sink 
        image: "maliksalman/grapes-sink:1.0.0"
        imagePullPolicy: Always
        resources:
          requests:
            memory: "500Mi"
            cpu: "375m"
          limits:
            memory: "768Mi"
            cpu: "500m"
        env:
          - name: NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: GRAPES_CONSUMER_GROUP
            value: go-raisins
