apiVersion: v1
kind: Pod
metadata:
  name: jump 
spec:
  containers:
  - name: jump
    image: alpine
    command:
      - sleep
      - 24h
    lifecycle:
      postStart:
        exec:
          command:
          - sh
          - -c
          - apk update && apk add bash curl jq bind-tools
