apiVersion: v1
kind: Pod
metadata:
  name: nginx-1
  labels:
    app: nginx
spec:
  containers:
  - name: nginx
    image: nginx
    ports:
    - containerPort: 80
      protocol: TCP
    lifecycle:
      postStart:
        exec:
          command:
          - sh
          - -cx
          - |
            echo "{\"name\":\"$HOSTNAME\", \"ver\":\"1.0\"}" > /usr/share/nginx/html/index.html
---
apiVersion: v1
kind: Pod
metadata:
  name: nginx-2
  labels:
    app: nginx
spec:
  containers:
  - name: nginx
    image: nginx
    ports:
    - containerPort: 80
      protocol: TCP
    lifecycle:
      postStart:
        exec:
          command:
          - sh
          - -cx
          - |
            echo "{\"name\":\"$HOSTNAME\", \"ver\":\"1.0\"}" > /usr/share/nginx/html/index.html
