apiVersion: v1
kind: Secret
metadata:
  name: nginx-secret
type: Opaque
data:
  quote.txt: V2UgYXJlIHRoZSBLbmlnaHRzIHdobyBzYXkgLi4uIE5JLgo=
  info.txt: dGhhdCBsYXN0IHF1b3RlIHdhcyBmcm9tIE1vbnR5IFB5dGhvbidzIEhvbHkgR3JhaWwK
---
apiVersion: v1
kind: Pod
metadata:
  name: nginx-with-secret
  labels:
    group: configs
spec:
  volumes:
  - name: secret-vol
    secret:
      secretName: nginx-secret
  containers:
  - name: nginx
    image: nginx
    ports:
    - containerPort: 80
      protocol: TCP
    command:
      - sh
      - -cx
      - |
        nginx -g "daemon off;" &
        while true; do
          echo "{\"name\":\"$HOSTNAME\", \"msg\":\"$(cat /usr/etc/secret/quote.txt)\"}" > /usr/share/nginx/html/index.html
          sleep 1;
        done

    volumeMounts:
    - name: secret-vol
      mountPath: /usr/etc/secret
      readOnly: true
